victorlaputskyproject/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
import blog.views as views
from blog.views import OrderListView, OrderDetailsView, OrderCreate, MainPage, ItemList, ItemAuthorList, ItemTagsList, ItemPublisherList, RegisterFormView, LoginFormView, LogoutView

urlpatterns = [
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^$', MainPage.as_view(), name='main'),
    url(r'^orders/$', OrderListView.as_view(), name='orders'),
    url(r'^orders/create/item=(?P<item_id>[0-9]+)/$', OrderCreate.as_view(), name='create_order'),
    url(r'^orders/(?P<pk>[0-9]+)/$', OrderDetailsView.as_view(), name='order_details'),
    url(r'^itemlist/$', ItemList.as_view(), name='items'),
    url(r'^itemlist/authors/(?P<author_id>[0-9]+)/$', ItemAuthorList.as_view(), name='author_items'),
    url(r'^itemlist/publisher/(?P<publisher_id>[0-9]+)/$', ItemPublisherList.as_view(), name='publisher_items'),
    url(r'^itemlist/tags/(?P<tag_id>[0-9]+)/$', ItemTagsList.as_view(), name='tag_items'),
    url(r'^item/(?P<item_id>[0-9]+)/$', views.item_view, name='item'),
    url(r'^register/$', RegisterFormView.as_view(), name='register'),
    url(r'^login/$', LoginFormView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User


class Items(models.Model):
    item_name = models.CharField(max_length=512, unique=True)
    item_image = models.ImageField(upload_to='images/', blank=True, null=True)
    item_publisher = models.ForeignKey('Publishers')
    author_id = models.ForeignKey('Authors')
    item_price = models.IntegerField(default='100')
    item_description = models.TextField(blank=True, max_length=512)
    release_date = models.DateField(default='2016-12-12')
    item_status = models.CharField(max_length=2, choices=[('a', 'Доступно'),('na', 'Не доступно')])
    item_genre = models.ManyToManyField('Tags', related_name='p')
    item_rating = models.DecimalField(max_digits=2,decimal_places=1, default=0.0, editable=False)

    def __str__(self):
        return self.item_name


class Authors(models.Model):
    author_name = models.CharField(max_length=512, unique=True)

    def __str__(self):
        return self.author_name


class Publishers(models.Model):
    publisher_name = models.CharField(max_length=512, unique=True)

    def __str__(self):
        return self.publisher_name


class Orders(models.Model):
    order_date = models.DateField(auto_now=True)
    order_adress = models.CharField(max_length=100, default='None', verbose_name=u'Желаемый адрес доставки')
    user_id = models.ForeignKey(User)
    item_id = models.ForeignKey(Items, verbose_name=u'Желаемая книга')
    # item_count = models.ManyToManyField('Items', related_name='p')
    order_status = models.CharField(max_length=2, choices=[('p', 'Комплектуется'),('d', 'Отправляется'),('f', 'Отправлено'), ('c', 'Отменено')], verbose_name=u'Статус заказа')
    order_comment = models.TextField(max_length=512, blank=True, verbose_name=u'Ваш комментарий (пожелания, номер телефона для связи, т.д.)')

    def __str__(self):
        return 'ID: {o.id} \nДата заказа: {o.order_date} \n Книга: {o.item_id}'.format(o=self)


class Comments(models.Model):
    user_id = models.ForeignKey(User)
    item_id = models.ForeignKey('Items')
    comment_date = models.DateTimeField(auto_now=True, )
    comment_text = models.TextField(max_length=512)

    def __str__(self):
        return 'User: {o.user_id}, Item: {o.item_id}, Date: {o.comment_date}, Text: {o.comment_text}'.format(o=self)


class Tags(models.Model):
    tag_name = models.CharField(max_length=200)

    def __str__(self):
        return self.tag_name

blog/forms.py
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django import forms
from blog.models import Items, Orders, Comments
from django.contrib.auth.models import User


class RegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ("username","email", "first_name", "last_name")
        field_classes = {'username': UsernameField, 'email': forms.EmailField, 'first_name': forms.CharField, 'last_name': forms.CharField}

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ('comment_text',)

    def save(self, commit=True):
        comment = super(CommentForm, self).save(commit=False)
        if commit:
            comment.save()
        return comment


class OrderForm(forms.ModelForm):
    class Meta:
        model = Orders
        fields = ('order_adress', 'order_comment')

    def save(self, commit=True):
        order = super(OrderForm, self).save(commit=False)
        if commit:
            order.save()
        return order

blog/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, FormView, CreateView, DetailView, UpdateView
from django.views.generic.base import View
from blog.models import Orders, Items, Comments, Publishers, Authors, Tags
from blog.forms import RegistrationForm, CommentForm, OrderForm
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect, JsonResponse
from django.contrib.auth import logout, login
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.auth.forms import AuthenticationForm
import random


class MainPage(TemplateView):
    template_name = 'First.html'

    def get_context_data(self, **kwargs):
        context = super(MainPage, self).get_context_data(**kwargs)
        item_list = Items.objects.get(id=random.randint(1,len(list(Items.objects.all()))))
        context['randombook'] = item_list
        topbooks = Items.objects.filter(item_publisher__id=1)[:5]
        context['topbooks'] = topbooks
        return context


class ItemList(TemplateView):
    template_name = 'Itemlist.html'

    def get_context_data(self, **kwargs):
        context = super(ItemList, self).get_context_data(**kwargs)
        j = Items.objects.all().order_by('-id')
        paginator = Paginator(j, 4)
        page = self.request.GET.get('page')
        try:
            items = paginator.page(page)
        except PageNotAnInteger:
            items = paginator.page(1)
        except EmptyPage:
            items = paginator.page(paginator.num_pages)

        context['itemlist'] = items
        context['authors'] = Authors.objects.all()
        context['publishers'] = Publishers.objects.all()
        context['tags'] = Tags.objects.all()
        return context


def item_view(request, **kwargs):
    form = CommentForm(request.POST or None)

    if request.method == 'POST' and form.is_valid():
        Comments.objects.create(user_id=request.user, item_id=Items.objects.get(id=kwargs['item_id']), **form.cleaned_data)

    object = Items.objects.get(id=kwargs['item_id'])

    recommended_objects = Items.objects.filter(item_publisher=object.item_publisher).exclude(id=object.id)[:4]
    comment_list = Comments.objects.filter(item_id=kwargs['item_id']).order_by('-comment_date')
    paginator = Paginator(comment_list, 5)
    page = request.GET.get('page')
    try:
        comments = paginator.page(page)
    except PageNotAnInteger:
        comments = paginator.page(1)
    except EmptyPage:
        comments = paginator.page(paginator.num_pages)
    return render(request, 'Items.html', {'comments': comments, 'item': object, 'recommended_books': recommended_objects, 'form': form})


class UserView(TemplateView):
    template_name = 'Users.html'
    model = User

    def dispatch(self, request, *args, **kwargs):
        print(request)
        print(kwargs)
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(UserView, self).get_context_data(**kwargs)
        j = User.objects.get(id=kwargs['user_id'])
        context['users'] = j
        return context


class RegisterFormView(FormView):
    form_class = RegistrationForm
    success_url = "/login/"
    template_name = "register.html"

    def form_valid(self, form):
       form.save()
       return super(RegisterFormView, self).form_valid(form)


class LoginFormView(FormView):
    form_class = AuthenticationForm
    template_name = "login.html"
    success_url = "/"

    def form_valid(self, form):
        self.user = form.get_user()
        login(self.request, self.user)
        return super(LoginFormView, self).form_valid(form)


class LogoutView(View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect("/")


class OrderListView(TemplateView):
    template_name = 'Orders.html'


    def get_context_data(self, **kwargs):
        context = super(OrderListView, self).get_context_data(**kwargs)
        user_ind = self.request.user
        j = Orders.objects.filter(user_id=user_ind)
        context['orders'] = j
        context['order_count'] = Orders.objects.filter(user_id=user_ind).count()
        context['profile'] = User.objects.get(id=user_ind.id)
        return context	


class OrderCreate(CreateView):

    form_class = OrderForm
    success_url = '/orders/'
    template_name = 'order_create.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['item'] = Items.objects.get(id=self.kwargs['item_id'])
        return context

    def form_valid(self, form):
        Orders.objects.create(user_id=self.request.user, order_status='p', item_id=Items.objects.get(id=self.kwargs['item_id']), **form.cleaned_data)
        return redirect('/orders/')


class OrderDetailsView(DetailView):
    model = Orders
    template_name = 'order_details.html'


class ItemAuthorList(TemplateView):
    template_name = 'authors_list.html'

    def get_context_data(self, **kwargs):
        context = super(ItemAuthorList, self).get_context_data(**kwargs)
        j = Items.objects.filter(author_id__id=kwargs['author_id'])
        paginator = Paginator(j, 3)
        page = self.request.GET.get('page')
        try:
            items = paginator.page(page)
        except PageNotAnInteger:
            items = paginator.page(1)
        except EmptyPage:
            items = paginator.page(paginator.num_pages)

        context['itemlist'] = items
        context['authors'] = Authors.objects.all()
        context['publishers'] = Publishers.objects.all()
        context['tags'] = Tags.objects.all()
        return context


class ItemPublisherList(TemplateView):
    template_name = 'authors_list.html'

    def get_context_data(self, **kwargs):
        context = super(ItemPublisherList, self).get_context_data(**kwargs)
        j = Items.objects.filter(item_publisher__id=kwargs['publisher_id'])
        paginator = Paginator(j, 3)
        page = self.request.GET.get('page')
        try:
            items = paginator.page(page)
        except PageNotAnInteger:
            items = paginator.page(1)
        except EmptyPage:
            items = paginator.page(paginator.num_pages)

        context['itemlist'] = items
        context['authors'] = Authors.objects.all()
        context['publishers'] = Publishers.objects.all()
        context['tags'] = Tags.objects.all()
        return context


class ItemTagsList(TemplateView):
    template_name = 'authors_list.html'

    def get_context_data(self, **kwargs):
        context = super(ItemTagsList, self).get_context_data(**kwargs)
        j = Items.objects.filter(item_genre__id=kwargs['tag_id'])
        paginator = Paginator(j, 3)
        page = self.request.GET.get('page')
        try:
            items = paginator.page(page)
        except PageNotAnInteger:
            items = paginator.page(1)
        except EmptyPage:
            items = paginator.page(paginator.num_pages)

        context['itemlist'] = items
        context['authors'] = Authors.objects.all()
        context['publishers'] = Publishers.objects.all()
        context['tags'] = Tags.objects.all()
        return context

blog/templates/Itemlist.html
{% extends "index.html" %}

{%  block head_title %}
   Доступные книги
{% endblock %}

{% block navbar %}
            <li><a href = "{% url 'main' %}"> Главная  </a></li>
            <li class="active"><a href = "{% url 'items' %}"><b>Книги </b></a></li>
              {% if user.is_anonymous %}
            <li><a href = "{% url 'register' %}">Регистрация</a></li>
            <li><a href = "{% url 'login' %}">Войти</a></li>
              {% endif %}
              {% if user.is_authenticated %}
            <li><a href = "{% url 'orders' %}">Мои заказы</a></li>
            <li><a href = "{% url 'logout' %}">Выйти </a></li>
              {% endif %}
    {% if user.is_superuser %}
             <li><a href = "/admin/">Админка</a></li>
               {% endif %}
<li>&nbsp&nbsp &nbsp&nbsp &nbsp&nbsp &nbsp&nbsp &nbsp&nbsp &nbsp&nbsp &nbsp&nbsp &nbsp&nbsp &nbsp&nbsp &nbsp&nbsp &nbsp&nbsp </li>

{% endblock %}
{% block content %}
 <div class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href = "{% url 'items' %}" class="maintext"><b>Все книги</b></a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">По авторам <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        {% for author in authors %}
                        <li><a href="{% url 'author_items' author_id=author.id %}">{{author.author_name}}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                                   <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">По издателям<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        {% for publisher in publishers %}
                        <li><a href="{% url 'publisher_items' publisher_id=publisher.id %}">{{publisher.publisher_name}}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">По тегам<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        {% for tag in tags %}
                        <li><a href="{% url 'tag_items' tag_id=tag.id %}">{{tag.tag_name}}</a></li>
                        {% endfor %}
                    </ul>
                </li>
            </ul>

        </div>
        <!--/.nav-collapse -->
    </div>
</div>

<!-- include javascript, jQuery FIRST -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>

<br>
{% for item in itemlist %}
<div class="panel panel-default animated flipInX">
    <div class="panel-heading">
              <h3 class="panel-title center"><b>{{ item.item_name }}</b></h3>
    </div>
            <div class="panel-body">    <div class="row">
    <div class="col-md-3"><div class="well"><div class="center"><a href="{% url 'item' item_id=item.id %}"><img src="/media/{{ item.item_image }}" width="115"/></a></div></div></div>
    <div class="col-md-8">{{item.item_description}}<br><br><br>
    <div class="well"><b>Цена:</b>{{ item.item_price }} руб. <b>Статус: </b>{{ item.get_item_status_display }} &nbsp&nbsp
    <a href="{% url 'item' item_id=item.id %}"><button type="button" class="btn btn-sm btn-primary">Перейти на страницу книги</button></a></div>
    </div>
    </div></div>
          </div>
{% empty %}
    <div id="centerLayer" class="center">У нас пока что нет книг по данной категории!</div>

    {% endfor %}
<div class="center">
     <div class="pagination">
    <span class="step-links">
        {% if itemlist.has_previous %}
            <a href="?page={{ itemlist.previous_page_number }}" class="maintext"><button type="button" class="btn btn-sm btn-primary"><b>Предыдущая страница</b></button></a>
        {% endif %}

        <span class="current">
            Страница {{ itemlist.number }} из {{ itemlist.paginator.num_pages }}.
        </span>

        {% if itemlist.has_next %}
            <a href="?page={{ itemlist.next_page_number }}" class="maintext"><button type="button" class="btn btn-sm btn-primary"><b>Следующая страница</b></button></a>
        {% endif %}
    </span>
</div>
</div>

{% endblock %}

blog/templates/Items.html
{% extends "index.html" %}

{%  block head_title %}
    {{ item.item_name }}
{% endblock %}
{% block navbar %}
            <li><a href = "{% url 'main' %}"> Главная  </a></li>
            <li class="active"><a href = "{% url 'items' %}"><b>Книги </b></a></li>
              {% if user.is_anonymous %}
            <li><a href = "{% url 'register' %}">Регистрация</a></li>
            <li><a href = "{% url 'login' %}">Войти</a></li>
              {% endif %}
              {% if user.is_authenticated %}
            <li><a href = "{% url 'orders' %}">Мои заказы</a></li>
            <li><a href = "{% url 'logout' %}">Выйти </a></li>
              {% endif %}
    {% if user.is_superuser %}
             <li><a href = "/admin/">Админка</a></li>
               {% endif %}
<li>&nbsp&nbsp &nbsp&nbsp &nbsp&nbsp &nbsp&nbsp &nbsp&nbsp &nbsp&nbsp &nbsp&nbsp &nbsp&nbsp &nbsp&nbsp &nbsp&nbsp &nbsp&nbsp </li>

{% endblock %}

{% block content %}

<br>
<br>
<br>
<div class="well">
<table border="0"><td>
<div class = "well"><img src=" {{ item.item_image.url}}" width="200" class="animated zoomIn"/></div></td><td>&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp</td>
<td>
<table class="table table-bordered">
<tbody>
</tr><td><b>&nbsp&nbsp  Название: </b></td><td>{{item.item_name}}</td></tr>
<tr> <td><b>&nbsp&nbsp  Автор: </b></td><td><a href="{% url 'author_items' author_id=item.author_id.id %}">{{item.author_id}}</a></td></tr>
<tr> <td><b>&nbsp&nbsp  Издательство: </b></td><td><a href="{% url 'publisher_items' publisher_id=item.item_publisher.id %}">{{ item.item_publisher }}</a></td></tr>
<tr> <td><b>&nbsp&nbsp  Категории: </b></td><td>{% for genre in item.item_genre.all %}
    <a href="{% url 'tag_items' tag_id=genre.id %}">{{genre}}</a> {% endfor %}</td></tr>
<tr> <td><b>&nbsp&nbsp  Цена: </b></td><td>{{item.item_price}} руб.</td></tr>
<tr> <td><b>&nbsp&nbsp  Статус: </b></td><td>{{item.get_item_status_display}}</td></tr>
</tbody>
</table>

    </td></table>

<div><b>Описание: </b>{{item.item_description}}</div>
<br>
<div class = "center"><a href="{% url 'create_order' item_id=item.id %}"><button type="button" class="btn btn-primary" name="item_id" value="{{ item.id }}">Купить эту книгу!</button></a></div>
</div>
<div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title center"><b>Еще книги от этого издательства</b></h3>
            </div>
            <div class="panel-body center">
              {% for book in recommended_books %} &nbsp;&nbsp;
<a href="{% url 'item' item_id=book.id %}"><img src="/media/{{ book.item_image }}" width="90"/> </a>&nbsp;
                {% empty %}
                  <i>К сожалению, пока что у нас больше нет книг этого издательства. Следите за обновлениями!</i>
              {%endfor%}
            </div>
          </div>



{% if user.is_authenticated %}
<div class="well"> <form action="" method="post">
      {% csrf_token %}
      <!-- as_p для того, чтобы каждый элемент формы был с новой строки -->
        <div class="form-group">
        <label for="comment_text">Ваш комментарий:</label>
        <textarea class="form-control" rows="5" id="comment_text" name="comment_text" placeholder="Ваше мнение о книге, рекомендации"></textarea>
        </div>
      <button type="submit" value="save">Оставить комментарий</button>
    </form></div>
{% endif %}

{% if user.is_anonymous %}
<div class="well"><div class="center">Вам нужно <b><a href = "{% url 'login' %}" class="maintext">войти</a></b>, чтобы оставлять комментарии!</div></div>
{% endif %}
<div class="well"><div class="center"><b>Комментарии</b></div>
    {%for comment in comments %}
        <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title center"><b><i>{{comment.comment_date}}, {{comment.user_id.first_name}} {{comment.user_id.last_name}}</i></b></h3>
            </div>
    <br><br>
    <div class="panel-body">{{comment.comment_text}}</div></div>
{% empty %}
    <div class="center">У этой книги еще не было комментариев!</div>
{% endfor %}
    <div class="center">
     <div class="pagination">
    <span class="step-links">
        {% if comments.has_previous %}
            <a href="?page={{ comments.previous_page_number }}" class="maintext"><b>Предыдущая страница</b></a>
        {% endif %}

        <span class="current">
            Страница {{ comments.number }} из {{ comments.paginator.num_pages }}.
        </span>

        {% if comments.has_next %}
            <a href="?page={{ comments.next_page_number }}" class="maintext"><b>Следующая страница</b></a>
        {% endif %}
    </span>
</div>
</div>
</div>
{% endblock %}

blog/templates/Orders.html
{% extends "index.html" %}

{%  block head_title %}
    Ваши заказы
{% endblock %}

{% block navbar %}
            <li><a href = "{% url 'main' %}"> Главная  </a></li>
            <li><a href = "{% url 'items' %}">Книги</a></li>
              {% if user.is_anonymous %}
            <li><a href = "{% url 'register' %}">Регистрация</a></li>
            <li><a href = "{% url 'login' %}">Войти</a></li>
              {% endif %}
              {% if user.is_authenticated %}
            <li class="active"><a href = "{% url 'orders' %}"><b>Мои заказы</b></a></li>
            <li><a href = "{% url 'logout' %}">Выйти </a></li>
              {% endif %}
    {% if user.is_superuser %}
             <li><a href = "/admin/">Админка</a></li>
               {% endif %}
<li>&nbsp&nbsp &nbsp&nbsp &nbsp&nbsp &nbsp&nbsp &nbsp&nbsp &nbsp&nbsp &nbsp&nbsp &nbsp&nbsp &nbsp&nbsp &nbsp&nbsp &nbsp&nbsp </li>

{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<br>
<div class="panel panel-default animated flipInX">
            <div class="panel-heading">
              <h3 class="panel-title center"><b>Ваш профиль</b></h3>
            </div>
<div class="panel-body center">
<table class="table table-bordered">
<tbody><tr> <td><b>Имя:</b> </td><td>{{ profile.first_name }}</td></tr>
<tr> <td><b>Фамилия:</b></td> <td>{{ profile.last_name }}</td></tr>
<tr> <td><b>Email:</b> </td><td>{{ profile.email }}</td></tr>
<tr> <td><b>Число сделанных заказов</b>:</td><td> {{ order_count }}</td></tr>

</table>
</div>
</div>


<div class="well animated fadeIn">
<p class="center"> <b>Ваши заказы </b></p>

{% for order in orders %}

    <div class = "well"><table border="0" bgcolor="#fdf5e6">
<tr><td><a href="{% url 'order_details' pk=order.id  %}" class = maintext><b>Номер <br> заказа: </b><br> {{ order.id }}</a></td> <td width="120"><a href="{% url 'order_details' pk=order.id  %}" class = maintext><b>Заказанная <br> книга</b><br>{{ order.item_id.item_name }} &nbsp</a></td><td width="100"><b>Дата заказа: </b><br>{{ order.order_date }} </td> <td width="100"><b>Адрес доставки: </b><br>{{ order.order_adress }} &nbsp&nbsp</td> <td width="150"><b>Статус:</b><br>{{order.get_order_status_display}}</td></tr>
    </table></div>
{% empty %}


    <div id="centerLayer">
    <div class="center">У вас нет заказов! Попробуйте поискать что-нибудь в нашем <b><a href="{% url 'items' %}" class="maintext">каталоге</a></b>, может найдете что-нибудь по душе! </div>
    </div>
{% endfor %}

</div>
{% endif %}

{% if user.is_anonymous %}
 <div id="centerLayer">
    <div class="center">Ой! Кажется, ты не вошел в систему! Пожалуйста, <a href="{% url 'items' %}" class="maintext"><b>войдите</b></a>, чтобы продолжить.</div>
    </div>
{% endif %}

{% endblock %}

blog/templates/Userlist.html
<!DOCTYPE html>
<html lang="en">
{%  block head_title %}
    Список пользователей
{% endblock %}
<body>
{% for user in userlist %}
    <div><a href="{% url 'user' user_id=user.id %}">{{ user }}</a></div>
{% endfor %}
</body>
</html>

blog/templates/Users.html
{% extends "index.html" %}
{%  block head_title %}
    Ваш профиль
{% endblock %}
{% block content %}
<body>
{{ users }}
</body>
{% endblock %}

blog/templates/order_details.html
{% extends 'index.html' %}

{% block navbar %}
            <li><a href = "{% url 'main' %}"> Главная  </a></li>
            <li><a href = "{% url 'items' %}">Книги</a></li>
              {% if user.is_anonymous %}
            <li><a href = "{% url 'register' %}">Регистрация</a></li>
            <li><a href = "{% url 'login' %}">Войти</a></li>
              {% endif %}
              {% if user.is_authenticated %}
            <li class="active"><a href = "{% url 'orders' %}"><b>Мои заказы</b></a></li>
            <li><a href = "{% url 'logout' %}">Выйти </a></li>
              {% endif %}
    {% if user.is_superuser %}
             <li><a href = "/admin/">Админка</a></li>
               {% endif %}
<li>&nbsp&nbsp &nbsp&nbsp &nbsp&nbsp &nbsp&nbsp &nbsp&nbsp &nbsp&nbsp &nbsp&nbsp &nbsp&nbsp &nbsp&nbsp &nbsp&nbsp &nbsp&nbsp </li>

{% endblock %}
{% block content %}
<br>
<br>
<style>
#centerLayer {
    margin-left: 30%; /* Отступ слева */
    width: 40%; /* Ширина слоя */
    background: #ecf8ff; /* Цвет фона */
    padding: 10px; /* Поля вокруг текста */
}
</style>



{% if user.is_authenticated and object.user_id.id == user.id %}
<div id="centerLayer">
    <div><b>Номер заказа:</b> {{ object.id }}</div>
    <div><b>Дата заказа:</b> {{ object.order_date }}</div>
    <div><b>Адрес получателя:</b> {{ object.order_adress }}</div>
    <div><b>Статус заказа:</b> {{ object.get_order_status_display }}</div>
    <div><b>Заказанная книга:</b> <a href = "{% url 'item' item_id=object.item_id.id %}" class = maintext>{{ object.item_id.item_name }}</a></div>
</div>
<br>
<div id="centerLayer"><i>Если вы передумали и хотите отменить заказ, напишите нам на электронную почту(info@domainhappy.by) с указанием номера Вашего заказа.</i></div>
{% endif %}
{% if user.is_anonymous %}
 <div id="centerLayer">
    <div class="center">Ой! Кажется, ты не вошел в систему! Пожалуйста, <a href="{% url 'items' %}" class="maintext"><b>войдите</b></a>, чтобы продолжить.</div>
    </div>
{% endif %}
{% endblock %}